language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "stacks-fifth-test";' -U postgres
script:
  - npm test
  - npm run build-client
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: stacksfifth
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: "1U6a2a61HP6N7SndRDQyDQ8ASPaZz+gnLcotTs5woshketoCx56/MDc8DTgjbrDliSLQslTILysdPFx0xJFAV0Mm64ABzxRoQdz8yrV5rF5SRUvXE+qLxA0fzoZw/WwYxPYTAlAauO7cZzc03CdGpf1AenuYhoEH4pBUKIRSeLa1zLgYuTh7JHyFuNmcsh07ZL6EfVIsF2QHaGWNQtYVywnphKtUzTy/GCocoJFR1LjRAvWHd6Z/dZbRn6FPzTGTNXRB+/L5iPkOcQFv6TKIrzxMl0rDNDDHN6TudiMmaZmztQTrQwPhj7d4DADo/ZiKI0nlvaFqCEzjIuWEqfzMK0PYxZaI3LmcIieM+HNbEa2EJq/ofroMd0cZpaYHp/RPE1twDKFX9vdSbJ4sInHmn6dMKf9xCuN6iHXFOfv0yMtEJD4Jv4MIeDBzqrfwEBiWRof5z84geDSZ/QCMccsz7A5ENv8nqK0oVsqbwwJTIxYUlpFNsLO6jxXQeHMG9uQnjW+xRtiqNjvDwGHwyWadfrJJoWA6PHLtLZYLXShJJVwwS1JfAN7Op8yo7MCMMgnMMUWWlF9GfIbmZxu7v/3gNodWavpc/4wdryAMrjWKYChQCtgg2zAEjlK1H7pzxtNdfKfodikTMj7rwdMvx72QSidmkiFgQQ+gkr7uCnuQNT0="