language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "stacks-fifth-test";' -U postgres
script:
  - npm test
  - npm run build-client

env:
  global:
    secure: KbYPJ1GzVG+CP5vSqKDXrRoKU8F1lByVTauDmJ1BAvSIxMeUX2osVpxPRTFXLt9GLpMLaJbUVe1AkqAIsvtXvqVy1yrFpCrHYY/RgDlJWEgjPEBy4doqcPL0N6ApszBqocUjFhQ+o5lmwJzLOb6RaLKglP51u2zapIQBVWnRHWn0ASkrh12yiILaelzMvHzrvJB5FywGQn6YXnGM6EvqboPogC3mkKWUCAsEPEYNycHui0oZ4XIdUbdgi0Z40dr5NS/yW9NGxs1EG6HWO51ITQdpmiNwHodGL8m/npGlbc1rzZU7s1LJRtLSi+tu5R51Xx3FYUBcorJCaESddqY62QsiG6J417yh7kcRaYEL8K4JZSwg9ZemL23myApNhNJnD/DK6RWLrk4wYT/8HzW6wjy1L0jewKpW8yswyNaZkkL+RMAldwzvLkZcapn4VVX4P+rkv+6AqKKXSPCE+6EEVNwPDa9DAMRpPoWjchltsJyZ6Oj5dktSYX6I0GAa0umphZ7oEGbJWClrv2MRZDOuQ3ysZy34Lj6dIz4WY28FGA5nj6a5hHLTu+YyZ+AHVBGch3e7PXh/t0qHYrGZ5GIKWdF/zYdtcWa4viodapdw5OVkd2hX0p0IqhcLOp/AA05pjeu9YA6y2p5G9+XAUL3ojzHs8X0uQP5D4k54MqXBQh4=
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: stacksfifth
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: aVg86xKT3lNLN+ESxipr0m5raprzGWGwEgTOFX8k/s0COO4tiEFyIVZR1SsftrFGVkK7/vk83NMQyFV13Smj/cok+kMw3THKKc5xF9cUNWfIS3UQsfMTc24wYOgpA13ijBMtAWOGOQbTZMS9sA9T8efYPTxnocJVQjur7gkRQhd+gz9B68bQcf00kg1EN0N0WjlUFLM6+QMpefg650uCY0FJAr8DtNrLcNpllpdU1Fm9tREn4vyFyT+VFNSIPmiFu02qs80EWOx7THwUezlPDNuRyWhRUJSLbZcWdUhxN7pH1XyMmfK89f5jJ3VUXzqIsq1hbIyOhwykrLN6KirAh+nZIhyUllL1ZoUN7PgYYj427jw4CyiXxih65AflBLXTWWXJohV4OQn3jQwwztEHTNGI8ksu5JLCjQwdqpPxVn7QR72h3I790hWw4M6ntGKulpQUO0zLnxJOHNeNR+kvla9WjGX/tH+FHK9zdba6t8EYAcQZJzfgg5ycRBzoIQZMOUJk9LdPn9CezxMb3+rfeFDInCdFKM0YFyy0upC4nwFZzxlev0IGlYLE01d9eeofqs3mSBUk8BYm4EwpmPO/hcuSG042U7Hvm/xF4quPFGT9xHez6jdgyXsxQB3ZVPdO8bqyrkNG7m9gr6ZwGtRWJw11OtMB/YErW5g30rCS3qk=
